name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run npm install
        run: |
          cd back/ecommerce-nicolas-pando
          npm install
      - name: Print npm logs
        run: cat back/ecommerce-nicolas-pando/npm-debug.log || true
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./back/ecommerce-nicolas-pando/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deploy-pim4:latest
